chore: disabling circle ci configs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,126 +1,126 @@
-version: 2.1
+# version: 2.1
 
-jobs:
-  build:
-    docker:
-      # specify the version
-      - image: circleci/golang:1.14
+# jobs:
+#   build:
+#     docker:
+#       # specify the version
+#       - image: circleci/golang:1.14
 
-      - image: circleci/mysql:5.7-ram
-        environment:
-          MYSQL_ROOT_PASSWORD: password
-          MYSQL_DATABASE: test_db
-          MYSQL_USER: user
-          MYSQL_PASSWORD: passw0rd
+#       - image: circleci/mysql:5.7-ram
+#         environment:
+#           MYSQL_ROOT_PASSWORD: password
+#           MYSQL_DATABASE: test_db
+#           MYSQL_USER: user
+#           MYSQL_PASSWORD: passw0rd
     
-    environment: # environment variables for the build itself
-      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
+#     environment: # environment variables for the build itself
+#       TEST_RESULTS: /tmp/test-results # path to where test results will be saved
 
-    working_directory: /go/src/github.com/sujal.kokh/gorm2.0
+#     working_directory: /go/src/github.com/sujal.kokh/gorm2.0
 
-    steps:
-      - checkout
+#     steps:
+#       - checkout
 
-      - run: mkdir -p $TEST_RESULTS # create the test results directory
+#       - run: mkdir -p $TEST_RESULTS # create the test results directory
 
-      - run:
-          name: Run unit test and generate coverage reports
-          command: |
-            go test -race -covermode=atomic -coverprofile=coverage.txt
-            gocov convert coverage.txt | gocov-xml > coverage.xml
-            bash <(curl -s https://codecov.io/bash) -f coverage.xml -t 07c8d869-e98f-4091-b67c-ca3b9525ff52
+#       - run:
+#           name: Run unit test and generate coverage reports
+#           command: |
+#             go test -race -covermode=atomic -coverprofile=coverage.txt
+#             gocov convert coverage.txt | gocov-xml > coverage.xml
+#             bash <(curl -s https://codecov.io/bash) -f coverage.xml -t 07c8d869-e98f-4091-b67c-ca3b9525ff52
             
-      - codecov/upload:
-          file: {{ coverage.xml }}
+#       - codecov/upload:
+#           file: {{ coverage.xml }}
 
-      - run: 
-          name: Create firebase Service Account Key files
-          command: |
-            echo "{\n\t\"type\": \"$FIREBASE_TYPE_DEV\",\n\t\"project_id\": \"$FIREBASE_PROJECT_ID_DEV\",\n\t\"private_key_id\": \"$FIREBASE_PRIVATE_KEY_ID_DEV\",\n\t\"private_key\": \"$FIREBASE_PRIVATE_KEY_DEV\",\n\t\"client_email\": \"$FIREBASE_CLIENT_EMAIL_DEV\",\n\t\"client_id\": \"$FIREBASE_CLIENT_ID_DEV\",\n\t\"auth_uri\": \"$FIREBASE_AUTH_URI_DEV\",\n\t\"token_uri\": \"$FIREBASE_TOKEN_URI_DEV\",\n\t\"auth_provider_x509_cert_url\": \"$FIREBASE_AUTH_PROVIDER_X509_CERT_URL_DEV\",\n\t\"client_x509_cert_url\": \"$FIREBASE_CLIENT_X509_CERT_URL_DEV\"\n}" > serviceAccountKey.json
+#       - run: 
+#           name: Create firebase Service Account Key files
+#           command: |
+#             echo "{\n\t\"type\": \"$FIREBASE_TYPE_DEV\",\n\t\"project_id\": \"$FIREBASE_PROJECT_ID_DEV\",\n\t\"private_key_id\": \"$FIREBASE_PRIVATE_KEY_ID_DEV\",\n\t\"private_key\": \"$FIREBASE_PRIVATE_KEY_DEV\",\n\t\"client_email\": \"$FIREBASE_CLIENT_EMAIL_DEV\",\n\t\"client_id\": \"$FIREBASE_CLIENT_ID_DEV\",\n\t\"auth_uri\": \"$FIREBASE_AUTH_URI_DEV\",\n\t\"token_uri\": \"$FIREBASE_TOKEN_URI_DEV\",\n\t\"auth_provider_x509_cert_url\": \"$FIREBASE_AUTH_PROVIDER_X509_CERT_URL_DEV\",\n\t\"client_x509_cert_url\": \"$FIREBASE_CLIENT_X509_CERT_URL_DEV\"\n}" > serviceAccountKey.json
       
-      - run:
-          name: Check the creation of the firebase Service Account Key files
-          command: |
-            cat serviceAccountKey.json
+#       - run:
+#           name: Check the creation of the firebase Service Account Key files
+#           command: |
+#             cat serviceAccountKey.json
 
-      - run:
-          name: Check the other files in the directory
-          command: |
-            ls
+#       - run:
+#           name: Check the other files in the directory
+#           command: |
+#             ls
 
 
-      - restore_cache: # restores saved cache if no changes are detected since last run
-          keys:
-            - go-mod-v4-{{ checksum "go.sum" }}
+#       - restore_cache: # restores saved cache if no changes are detected since last run
+#           keys:
+#             - go-mod-v4-{{ checksum "go.sum" }}
 
-      - run:
-        # Our primary container isn't MYSQL so run a sleep command until it's ready.
-            name: Waiting for MySQL to be ready
-            command: |
-              for i in `seq 1 10`;
-              do
-                nc -z 127.0.0.1 3306 && echo Success && exit 0
-                echo -n .
-                sleep 1
-              done
-              echo Failed waiting for MySQL && exit 1
+#       - run:
+#         # Our primary container isn't MYSQL so run a sleep command until it's ready.
+#             name: Waiting for MySQL to be ready
+#             command: |
+#               for i in `seq 1 10`;
+#               do
+#                 nc -z 127.0.0.1 3306 && echo Success && exit 0
+#                 echo -n .
+#                 sleep 1
+#               done
+#               echo Failed waiting for MySQL && exit 1
 
-      - run:
-          name: Run unit tests
-          environment: # environment variables for the database url and path to migration files
-            CONTACTS_DB_URL: "user:passw0rd@tcp(localhost:3306)/test_db?charset=utf8&parseTime=True&loc=Local"
-            CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
+#       - run:
+#           name: Run unit tests
+#           environment: # environment variables for the database url and path to migration files
+#             CONTACTS_DB_URL: "user:passw0rd@tcp(localhost:3306)/test_db?charset=utf8&parseTime=True&loc=Local"
+#             CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
 
-          # store the results of our tests in the $TEST_RESULTS directory
-          command: |
-            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
-            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
+#           # store the results of our tests in the $TEST_RESULTS directory
+#           command: |
+#             PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
+#             gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
       
-      - run: 
-          name: Build the golang project  
-          command: go build
+#       - run: 
+#           name: Build the golang project  
+#           command: go build
       
-      - save_cache:
-                  key: go-mod-v4-{{ checksum "go.sum" }}
-                  paths:
-                    - "/go/pkg/mod"
+#       - save_cache:
+#                   key: go-mod-v4-{{ checksum "go.sum" }}
+#                   paths:
+#                     - "/go/pkg/mod"
 
-      - run:
-          name: Start service
-          environment:
-            DB_HOST: "localhost"
-            DB_PORT: "3306"
-            DB_NAME: "gorm_two"
-            DB_USER: "root"
-            DB_PASS: "password"
-            # CONTACTS_DB_URL: "user:passw0rd@tcp(localhost:3306)/test_db?charset=utf8&parseTime=True&loc=Local"
-            CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
-          command: ./gorm2.0
-          background: true # keep service running and proceed to next step
+#       - run:
+#           name: Start service
+#           environment:
+#             DB_HOST: "localhost"
+#             DB_PORT: "3306"
+#             DB_NAME: "gorm_two"
+#             DB_USER: "root"
+#             DB_PASS: "password"
+#             # CONTACTS_DB_URL: "user:passw0rd@tcp(localhost:3306)/test_db?charset=utf8&parseTime=True&loc=Local"
+#             CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
+#           command: ./gorm2.0
+#           background: true # keep service running and proceed to next step
 
-      - run:
-          name: Validate service is working
-          command: |
-            sleep 5
-            curl http://localhost:8000
+#       - run:
+#           name: Validate service is working
+#           command: |
+#             sleep 5
+#             curl http://localhost:8000
 
-      - store_artifacts: # upload test summary for display in Artifacts
-          path: /tmp/test-results
-          destination: raw-test-output
+#       - store_artifacts: # upload test summary for display in Artifacts
+#           path: /tmp/test-results
+#           destination: raw-test-output
       
-      - store_test_results: # upload test results for display in Test Summary
-          path: /tmp/test-results
+#       - store_test_results: # upload test results for display in Test Summary
+#           path: /tmp/test-results
       
 
-      # # specify any bash command here prefixed with `run: `
-      # - run: go get -v -t -d ./...
-      # - run: go test -v ./...
+#       # # specify any bash command here prefixed with `run: `
+#       # - run: go get -v -t -d ./...
+#       # - run: go test -v ./...
 
-orbs: 
-  codecov: codecov/codecov@1.1.1 
+# orbs: 
+#   codecov: codecov/codecov@1.1.1 
 
-workflows:
-  version: 2
-  build-workflow:
-    jobs:
-      - build
+# workflows:
+#   version: 2
+#   build-workflow:
+#     jobs:
+#       - build
